### ISSUE TITLE
Doesn't work for Mac (R7, Big Sur)

### ISSUE THREAD

**Issue by JackLiu00521** [arendvw/ScriptParasite#10]
Hi arendvw,

The plugin works awesome when I develop on PC and really save the day (big thanks!)
However, when I try it on Mac, it doesn't work, and the warning message shows "Solution exception:Value cannot be null.
Parameter name: objectToConvert"

<img width="1551" alt="image" src="https://user-images.githubusercontent.com/12693623/131250541-ba63c3de-5572-4074-b5a7-7942cd3eef5d.png">

https://discourse.mcneel.com/t/c-scripteditor-is-still-a-pain-everywhere/64379/103
I have tried both methods you mentioned here, but none of them work for me : (
Is there any clue to fix it?
I'm using Rhino7(7.9.21222) on macOS Big Sur, with ScriptParasite 1.1.1 (from PackageManager).

Also, I'm willing to test any solution if there's no Mac available for you.
Thank you again for developing such a nice tool for the community! 😀

**Comment by arendvw** [comment]
Hi JackLui,

This is a bug due to the script editor being changed in Mac OSX

I've published ScriptParasite 1.1.2 for mac, this should resolve the issue for Rhino for Mac 7

[ScriptParasite-1.1.2.zip](https://github.com/arendvw/ScriptParasite/files/7073051/ScriptParasite-1.1.2.zip)

Does this work for you?

**Comment by JackLiu00521** [comment]
Yes! It works perfectly right now!

Thanks for your quick support 🙌

Cheers!

**Comment by arendvw** [comment]
Awesome!

**Comment by JackLiu00521** [comment]
Haha, originally I struggled for a while that I can't use autocomplete in VS Code with files from my PC.

Then I noticed you also refreshed the reference location for Mac in .csproj when I regenerate files through Mac.

Now it works, fantastic!!! 🤩
