### ISSUE TITLE
.net famework version in GrasshopperScripts.csproj file

### ISSUE THREAD

**Issue by ZacZhangzhuo** [arendvw/ScriptParasite#15]
Terminal Error Code : `Error: The primary reference "Grasshopper" could not be resolved because it has an indirect dependency on the assembly "RhinoCommon, Version=7.13.21299.17001, Culture=neutral, PublicKeyToken=552281e97c755530" which was built against the ".NETFramework,Version=v4.8" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.5.2".`

Notice that I have had.NETFramework 4.8 in my PC, I can not install v4.5.2 as the installer cannot do that. I so changed GrasshopperScripts.csproj line:
`<TargetFramework>net452</TargetFramework>`
into
`<TargetFramework>net480</TargetFramework>`
it works for me, but I have to change every time. Hope this .NETFramework issue can be fixed. Thank you.

**Comment by arendvw** [comment]
Hi Zac, Thanks a lot for opening this issue. Attached is a version of scriptparasite built against framework 4.8. Where do you get this issue? (Do you have a screenshot?)

I've been trying to accomplish maximum backwards compatibility; but it might be needed to break this at some point. Do you mean by "Change it every time", every time that a new script parasite version is released?

**Comment by ZacZhangzhuo** [comment]
Hi, thanks for your reply. 

It worked well on me days ago but now I got this error. I think the reason is I downloaded a later .NET framework or something. I got this error in my VSCode terminal, then VSCode cannot sense all the namespaces of Rhino or GH.
![image](https://user-images.githubusercontent.com/57562250/160101572-05af674b-2e63-4dcd-aba1-fd0feadcda6a.png)

> "Change it every time"  I mean every time I create a new C# component and Scriptparasite, the .net version in .csproj would be net452 by default and I have to change manually.

I think you may add some code the sense the .net version on the PC or something.

**Comment by arendvw** [comment]
Ah check. I think Rhino 6 and 7 are build against dotnet 4.8; but I'm not sure on if this would also work on mac osx. Thanks for the report; I need a bit of time to check out and resolve this issue.

**Comment by ZacZhangzhuo** [comment]
Thanks! we look forward to
