### ISSUE TITLE
Incorrect file output in macos

### ISSUE THREAD

**Issue by AxlaDesign** [arendvw/ScriptParasite#2]
Hello, I'm using ScriptParasite on macos and it seems that the output folder is incorrect, as the .cs file gets a extra backslash (unix systems index into folders using forward slashes so I guess this is the root of the problem).
See the folder below, which is the output folder (Folder input in Grasshopper looks like: `Users/MyProject/Scripts/`)

![image](https://user-images.githubusercontent.com/65452706/98135153-cead9000-1ebf-11eb-8541-7a4c4ce3f1e2.png)
Notice the added backslash at the start of the name, I assume that it should be "MyScript3d-360.cs"

![image](https://user-images.githubusercontent.com/65452706/98135219-dec56f80-1ebf-11eb-9d4c-90881de7cedd.png)
In Visual Studio, the correct file is not found.

**Comment by arendvw** [comment]
Thanks, this issue was fixed over a year ago by Andrew Heumann, but I did not release a new version. I'll do that shortly, could you then check again?

**Comment by arendvw** [comment]
There is a version 1.0.3 available on [food4rhino](https://www.food4rhino.com/app/scriptparasite-grasshopper). 

If you use the yak version, I'll try to release a compatible version later on.

Does this work for you?

**Comment by AxlaDesign** [comment]
Thanks! It works now with Visual Studio 2019 for mac. Did not get it to sync with VSCode.
