### ISSUE TITLE
Make component smaller

### ISSUE THREAD

**Issue by dilomo** [arendvw/ScriptParasite#9]
@arendvw I got another idea, more like proposal rather than a bug. What if we remove the Enable button switch so that the component becomes one line only? Enabling and disabling would be done with regular context actions of GH and the component will show disabled if no folder or in group with a script? Maybe I can try these days to see if would be okey usability wise..

**Comment by arendvw** [comment]
I'm not against it. Main reason there's an enable button is that it's faster for development I guess :)

Might make it simpler.

**Comment by dilomo** [comment]
Yeah better not bother if it works for now. And hiding the enable would not
be very grasshopper way so i decided to close this.

**Comment by arendvw** [comment]
Cool, that's clear, I'll close this issue.
